version: "3.9"
services:
  database:
    image: mysql
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3307:3306"
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on: 
      - database
    restart: on-failure
    env_file:
      - .env